version: '3.8'

services:
  db:
    image: 'postgres:15.2-alpine'
    ports:
      - "5432:5432"
    container_name: db
    environment:
      POSTGRES_DB: python_fastapi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d python_fastapi_db -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
